"""
config.py

Single source of truth for every hyperparameter and path in the project.
Nothing in any training script or notebook should hardcode a number that
lives here.
"""

import random
from pathlib import Path

import numpy as np
import torch


# ---------------------------------------------------------------------------
# Reproducibility
# ---------------------------------------------------------------------------

SEED = 42


def set_seeds(seed: int = SEED) -> None:
    """
    Set random seeds for Python, NumPy, and PyTorch (CPU and GPU) and put
    cuDNN into deterministic mode.

    Deterministic cuDNN trades a little throughput for run-to-run
    reproducibility, which matters more here than raw training speed. Note
    that the LLaMA narrative text is generated by the Ollama runtime and is
    only partially controlled by the seed passed in src/models/llama.py.
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def seeded_generator(seed: int = SEED) -> torch.Generator:
    """Return a torch.Generator seeded for DataLoader shuffling / splits."""
    return torch.Generator().manual_seed(seed)


# ---------------------------------------------------------------------------
# Patch extraction
# ---------------------------------------------------------------------------

GRID_SIZE = 8       # divide each image into an 8x8 grid (64 patches total)
PATCH_SIZE = 380    # resize each patch to 380x380 before passing to EfficientNet


# ---------------------------------------------------------------------------
# EfficientNet-B4
# ---------------------------------------------------------------------------

EFFICIENTNET_MODEL = "efficientnet_b4"
EFFICIENTNET_IMG_SIZE = 380
EFFICIENTNET_LR = 1e-4
EFFICIENTNET_WEIGHT_DECAY = 1e-2
EFFICIENTNET_BATCH_SIZE = 16
EFFICIENTNET_EPOCHS = 50
EFFICIENTNET_NUM_WORKERS = 2
EFFICIENTNET_DROP_RATE = 0.3        # head dropout
EFFICIENTNET_DROP_PATH_RATE = 0.2   # stochastic depth across the backbone

# RDD2022 is multi-label: an image can contain more than one defect type, so
# each of the four defect classes gets its own independent sigmoid output.
# "No defect" (background) is implicit -- it's what a zero vector means, not
# a class of its own.
RDD2022_NUM_CLASSES = 4     # D00 + D10 + D20 + D40
RDD2022_DEFECT_THRESHOLD = 0.5   # sigmoid cutoff for "this defect is present"
MVTEC_NUM_CLASSES = 2       # normal + anomalous

# Kept separate from EFFICIENTNET_BATCH_SIZE/EPOCHS/NUM_WORKERS so retuning
# the RDD2022 notebook run doesn't also retune scripts/train_mvtec.py.
MVTEC_BATCH_SIZE = 32
MVTEC_EPOCHS = 20
MVTEC_NUM_WORKERS = 4


# ---------------------------------------------------------------------------
# DQN
# ---------------------------------------------------------------------------

DQN_LR = 1e-4
DQN_GAMMA = 0.99                # discount factor for future rewards
DQN_BATCH_SIZE = 64
DQN_REPLAY_BUFFER_SIZE = 50000
DQN_TARGET_UPDATE_FREQ = 500    # copy weights to target network every N steps
DQN_EPSILON_START = 1.0
DQN_EPSILON_END = 0.05
DQN_EPSILON_DECAY = 10000       # steps over which epsilon anneals
DQN_TRAIN_STEPS = 200000
DQN_STEP_PENALTY = -0.1         # reward subtracted per step to encourage efficiency
DQN_DEFECT_REWARD = 1.0         # reward for finding a defective patch

# The agent has an explicit "stop" action (index GRID_SIZE^2). Stopping ends
# the episode and pays a terminal bonus proportional to the fraction of the
# image's defects already found, minus a penalty for each known defective
# patch left un-inspected. Together these make stopping worthwhile only once
# recall is already high -- which is what turns "patch selection" into a real
# adaptive decision instead of a fixed sweep.
DQN_STOP_BONUS = 3.0            # terminal reward at recall = 1.0
DQN_MISS_PENALTY = 1.0          # subtracted per defective patch missed at stop
DQN_MAX_INSPECT_BUDGET = 40     # inference hard cap if the agent never stops


# ---------------------------------------------------------------------------
# LLaMA 3.2 Vision (via Ollama)
# ---------------------------------------------------------------------------

LLAMA_MODEL = "llama3.2-vision"
OLLAMA_HOST = "http://localhost:11434"


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

ROOT_DIR = Path(__file__).parent

DATA_DIR = ROOT_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

RDD2022_DIR = RAW_DIR / "rdd2022"
MVTEC_DIR = RAW_DIR / "mvtec"

CHECKPOINT_DIR = ROOT_DIR / "checkpoints"
RDD2022_CHECKPOINT = CHECKPOINT_DIR / "efficientnet_rdd2022.pth"
MVTEC_CHECKPOINT = CHECKPOINT_DIR / "efficientnet_mvtec.pth"
DQN_CHECKPOINT = CHECKPOINT_DIR / "dqn.pth"
